[package]
name = "VustNexus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-macro = {path = "derive-macro"}
macroquad = "0.3.25"
interpolation = "0.2.0"


